### PR TITLE
Adds basic in-repo documentation.

### PR DESCRIPTION
**Pull request by Wilto**
A lot of these additions are just to raise some discussion—versioning, branch strategy, and the like. Happy to sit down whenever you guys are available to talk things through!

### CODE REVIEW

**Comment by Wilto** [comment]
Oh, I misread your comment as saying that Rangy _would_ be concat’d into ArteJS. What do you think, @leobalter? I’m inclined to keep it separate.

**Comment by leobalter** [comment]
Rangy versions are still unstable to separate it. It's better to keep this locked version inside.

Maybe, for the future, replace it or help the Rangy project to make it more stable.

**Comment by leobalter** [comment]
In my process of code refactoring within the new unit tests I'm being able to remove the dependencies on rangy.

**Comment by Wilto** [comment]
Cool, cool. I’m gonna merge this as it stands now, then—we can strike that line along with the refactor.

**Comment by Wilto** [comment]
(+1’d by @chriskwan via Gitter)

**Pull request merged**
