### PR TITLE
Fix unit tests to run multiple versions of jQuery

### LINKED ISSUE #62: Fix unit tests to run multiple versions of jQuery
Currently we have the beginnings of support for this but some things are hard-coded to use jQuery 1.9. Once #60 is fixed, we should get this working so we can easily test multiple versions of jQuery.

### PR DESCRIPTION
**Pull request by chriskwan**
Fixes #62

### CODE REVIEW

**Comment by chriskwan** [comment]
Decided to go with just running qunit multiple times with a different version of jQuery in the query string instead of using qunit-composite with the all.html page because there was an issue with running it that way in travis and it took a long time running it in grunt.

Next steps are to remove the qunit-composite stuff and do a little minor refactoring so we don't hard-code the different jQuery versions all over the place if possible.

**Comment by chriskwan** [comment]
This should be all set now. We are running tests against multiple versions of jQuery ("1.9.1", "1.10.2", "1.11.2", "2.0.0", "2.1.3") in travis and you can run them manually by doing `grunt qunit:all`.

**Comment by chriskwan** [comment]
Can I get a code review? @gshenar, @nsp37, and anyone else.

**Comment by nsp37** [comment]
Looks fine to me @chriskwan

**Comment by chriskwan** [comment]
Thanks, will merge.

**Pull request merged**
