### PR TITLE
Fix some build stuff

### LINKED ISSUE #34: Drop `jslint` reporter file
Is there any usage of the JSHint report (in JSLint style) usage or should we drop it? I didn't find anything from the Travis CI or similar that could use it.

Actually, the report is omitting a JSHint check issue in the stdout.

https://github.com/vistaprint/ArteJS/blob/master/Gruntfile.js#L25-L26

### LINKED ISSUE #40: Create an EditorConfig file
This way the code style will be preserved

### LINKED ISSUE #42: Implement code coverage
grunt-qunit-coverage should cover that.

### PR DESCRIPTION
**Pull request by leobalter**
This updates the package.json and fixes some JSHint errors found after exposing the results to the stdout. I'll fix more things to complement this PR, but feel free to start reviewing.

Closes #42
Closes #40
Closes #34

### CODE REVIEW

**Comment by leobalter** [comment]
Interesting, running from my machine I get 69% of coverage on 449 assertions: 

```
>> 449 assertions passed (5964ms)
>> Coverage:
>> -  Lines: 69.4%
>> -  Statements: 69.34%
>> -  Functions: 71.11%
>> -  Branches: 58.41%

Done, without errors.
```

While travis-ci gets 67% and 415 assertions

```
>> 415 assertions passed (5672ms)
>> Coverage:
>> - Lines: 67.69%
>> - Statements: 67.63%
>> - Functions: 70.43%
>> - Branches: 56.14%
```

Changed my node environment, reinstalled my node modules and I don't know how to get these 415 assertions only.

**Comment by leobalter** [comment]
This PR is ready for review and landing after that.

It sets a kickoff fix on the build stuff and sets the tests coverage report to guide us to refactor the code.

**Comment by Wilto** [comment]
Hey guys!

@leobalter spent some time reorganizing things for the sake of consistency and to facilitate future testing, but there’s a lot in here to go over. I was hoping we could set aside some time with you guys tomorrow to talk about how we’ll discuss PRs, issues, and suggestions going forward—I’m guessing we’ll have a lot of back-and-forth going on, asking questions and such, and walking through changes like the ones in here.

No need to worry about merging this just yet, but we’re looking forward to discussing it with you soon!

**Comment by chriskwan** [comment]
How about tomorrow (Friday 2/13) at 1:00 pm EST? I emailed you guys a calendar invite.

**Comment by leobalter** [comment]
Ok, branch squashed and commits are now organized.

After a review on internal gitter chat, I'm merging this.

**Pull request merged**
